#include "DXUT.h"
#include "Matrices.h"

XMVECTOR vUpVec;
XMMATRIX PROJECTION_MATRIX;
XMMATRIX VIEW_MATRIX;
XMMATRIX WORLD_MATRIX;
XMMATRIX WORLDVIEW_MATRIX;
XMMATRIX WORLDVIEWPROJECTION_MATRIX;
XMMATRIX texScaleBiasMat;
XMMATRIX SHADOW_TEX_MATRIX;
XMMATRIX SHADOW_TEX_MATRIX0;
XMMATRIX SHADOW_TEX_MATRIX1;
XMMATRIX SHADOW_TEX_MATRIX2;

float dx;
float dy;